### ISSUE TITLE
Fail to render map

### ISSUE THREAD

**Issue by flohoff** [hholzgra/maposmatic-vagrant#1]
Hi Hartmut,
just tried the container and i get a render failure - Looking into the syslog i find this:

Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: /home/maposmatic/ocitysmap/stylesheet/maposmatic-printable/inc/entities.xml.inc:2: I/O warning : failed to load external entity "/home/maposmatic/ocitysmap/stylesheet/maposmatic-printable/inc/settings.xml.inc"
Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: %settings;
Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: ^
Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: %settings;
Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: ^
Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: I/O warning : failed to load external entity "/home/maposmatic/ocitysmap/stylesheet/maposmatic-printable/inc/fontset-settings.xml.inc"
Mar 25 06:44:52 vagrant-ubuntu-wily-64 python[24816]: I/O warning : failed to load external entity "/home/maposmatic/ocitysmap/stylesheet/maposmatic-printable/inc/datasource-settings.xml.inc"

Indeed the settings.xml.inc does not exist - there is a settings.xml.inc.template file in the same directory.

I guess the same happened to 

fontset-settings.xml.inc.template

Which is also only there as a template.

This is all with MapOSMatic MAP Style. I just tried again with CartoOSM and that seems to work. 
Flo

**Comment by hholzgra** [comment]
The actual fault is a wrong ocitysmap.conf ... I know that currently only CartoOSM is properly set up, so this should be the only configured style ...

But having more styles properly configured is a short term goal ...

**Comment by hholzgra** [comment]
Fixed by https://github.com/hholzgra/maposmatic-vagrant/commit/ad313ddb66db0c8222c9a2f968c02ec5d12b6cc5
