### ISSUE TITLE
AttributeError at / module 'www.settings' has no attribute 'WEBLATE_BASE_URL'

### ISSUE THREAD

**Issue by dimmer123** [hholzgra/maposmatic-vagrant#10]
After installation when I  open http://localhost:8000/ it gives the error.

AttributeError
module 'www.settings' has no attribute 'WEBLATE_BASE_URL'
/home/maposmatic/maposmatic/www/maposmatic/context_processors.py in all, line 151
/usr/bin/python3
3.6.7
['/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/home/maposmatic/maposmatic',  '/home/maposmatic/ocitysmap',  '/home/maposmatic/ocitysmap',  '/home/maposmatic/ocitysmap/ocitysmap/indexlib/..',  '/home/maposmatic/ocitysmap/ocitysmap/indexlib/../indexlib/..']
Пт, 17 Май 2019 09:28:32 +0200

**Comment by chatelao** [comment]
Same here: [Full error dump on Google Docs](https://docs.google.com/document/d/1EBkT_CZTjrmQbKtyw5izEP8KwIxJZvWE36otYwWgeJw/edit?usp=sharing)

**Comment by chatelao** [comment]
Solution: see the patch below

diff --git a/files/settings_local.py b/files/settings_local.py
index d69cba0..6e008f8 100644
--- a/files/settings_local.py
+++ b/files/settings_local.py
@@ -192,3 +192,4 @@ EXTRA_FOOTER = ''
 # show this in a warning box on top of the page when set
 MAINTENANCE_NOTICE = ''

+WEBLATE_BASE_URL = ''

**Comment by dimmer123** [comment]
Chatelao thank you!
What is login and password to log in the virtual machine?

**Comment by hholzgra** [comment]
Fixed by https://github.com/hholzgra/maposmatic-vagrant/commit/26cec173ed369cf12cf7e55af7ff9b94482bc239

**Comment by hholzgra** [comment]
dimmer123: it uses a standard Ubuntu base box, so the box has users "root" and "vagrant"; both using the password "vagrant"

You should not need these though, you should be able to log in without password with "vagrant ssh", and gain root access with passwordless "sudo", once you're logged in

**Comment by chatelao** [comment]
Agree: Best way is

`vagrant ssh`

**Comment by chatelao** [comment]
And to gain root:

`sudo su`

is always a great way.
