### ISSUE TITLE
module 'www.settings' has no attribute 'MAX_BOUNDING_OUTER'

### ISSUE THREAD

**Issue by mapet68** [hholzgra/maposmatic-vagrant#18]
I got this:

Request Method: | GET
-- | --
http://localhost:8000/
1.11.11
AttributeError
module 'www.settings' has no attribute 'MAX_BOUNDING_OUTER'
/home/maposmatic/maposmatic/www/maposmatic/context_processors.py in all, line 168
/usr/bin/python3
3.6.8
['/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages',  '/home/maposmatic/maposmatic',  '/home/maposmatic/ocitysmap',  '/home/maposmatic/ocitysmap',  '/home/maposmatic/ocitysmap/ocitysmap/indexlib/..',  '/home/maposmatic/ocitysmap/ocitysmap/indexlib/../indexlib/..']
Śr, 23 Paź 2019 11:54:13 +0200

**Comment by hholzgra** [comment]
Weird, I thought I had that fixed and pushed ...

Unfortunately I'm on a meeting all week, and don't have access to my development machine at home right now, so I probably won't be able to look into this before the weekend.

But putting a 

MAX_BOUNDING_OUTER=False

into the /home/maposmatic/maposmatic/www/settings_local.py, followed by "systemctl restart apache2" should fix your installation for now ...

**Comment by mapet68** [comment]
God bless you. Have a good day ;)

**Comment by hholzgra** [comment]
Should be fixed now ....
