### ISSUE TITLE
water_polygons_z1.shp' does not exist on OpenTopoMap STYLE

### ISSUE THREAD

**Issue by mapet68** [hholzgra/maposmatic-vagrant#19]
File "/home/maposmatic/ocitysmap/ocitysmap/maplib/map_canvas.py", line 97, in __init__
    mapnik.load_map(self._map, stylesheet.path)
RuntimeError: Shape Plugin: shapefile '/home/maposmatic/styles/OpenTopoMap/mapnik/data/water-polygons-generalized-3857/water_polygons_z1.shp' does not exist  encountered during parsing of layer 'waterpolys_z1' in Layer at line 72 of '/home/maposmatic/styles/OpenTopoMap/mapnik/opentopomap.xml'

How to generate this file?

**Comment by hholzgra** [comment]
The original download server no longer exists, I'm now hosting the last version of the file I still had here:

http://osm-baustelle.de/downloads/water-polygons-generalized-3857.zip
