### ISSUE TITLE
get-stylesheets script needs to handle bad downloads 

### ISSUE THREAD

**Issue by hartmut-mariadb** [hholzgra/maposmatic-vagrant#20]
During the recent Natural Earth outage invalid ZIP files were downloaded, replacing the previously cached download files and then leading to loss of the actual shapefiles as these invalid ZIP files failed to unpack ...

So the script needs some extra code to ensure that new downloads are actually functional, and to preserve older downloads until it's confirmed that the new ones actually work ...

**Comment by hholzgra** [comment]
The get-stylesheets script now checks whether wget returned with an error code, and in case of successful download whether the downloaded file is really a ZIP or compressed tar archive. If it isn't the downloaded file is deleted and replaced by then archive copy of the previous file.
