### ISSUE TITLE
places.sql.gz is 404ing

### ISSUE THREAD

**Issue by simonhyde** [hholzgra/maposmatic-vagrant#23]
During the build process inc/places-database.sh tries to fetch places.sql.gz from https://www.osm-baustelle.de/downloads/places.sql.gz but that URL is returning a 404, so this step fails because the file is empty.

What's supposed to be in this file? Can you make it available somewhere?

Please excuse previous (closed) issue filed under the wrong account.

**Comment by hholzgra** [comment]
No idea how/when this got lost :(

I restored an older copy from a backup right now, but there may be a few places missing, or returning a wrong OSM id, for now while I have to re-generated the actual file from current OSM data ...

**Comment by simonhyde** [comment]
Oh, sorry, I mis-typed the name in my original request, the name needs to be place.sql.gz, not places.sql.gz

**Comment by hholzgra** [comment]
The file now exists under both names. 

Unfortunately the upstream file I used to generate it from has no longer been updated in years, so I will eventually find a different way to directly generate it from OSM planet file data, but that will be a different issue

**Comment by hholzgra** [comment]
Regenerate issue is now issue #46, closing this one
