### ISSUE TITLE
Error on "vagrant up"

### ISSUE THREAD

**Issue by chatelao** [hholzgra/maposmatic-vagrant#9]
Aktuell läuft bei mir das "vagrant up" nicht durch (mit "Switzerland". Kann es sein, dass sich die Versionen verschoben haben?

**Comment by hholzgra** [comment]
An welcher Stelle scheitert es denn? Ich hatte zwei kleinere Änderungen noch nicht gepuscht (gerade nachgeholt), kann mir aber nicht vorstellen, dass die mit dem Problem zu tun haben.

Bei mir lief gestern alles ordentlich durch. Nur der osm.de Stil funktioniert gerade nicht, aber das ist ein bekanntes Problem mit dem Stil selbst, bzw. mit Wegfall der "simplified" Shapefiles von Christof Hormann und Jochen Topf.

**Comment by chatelao** [comment]
Sorry, so präzise :-) habe ich es noch nicht. Ich melde mich wieder.

**Comment by chatelao** [comment]
Also: "git" ändert beim Auschecken auf **Windows** das Zeilenende von LF auf CRLF. damit war das `provision.sh` für Linux beschädigt.
